remote_theme: pages-themes/leap-day@v0.2.0
url: https://asaragga.github.io/ARE
plugins:
- jekyll-remote-theme 
title: ARE ğŸŒ
description: ValorizaÃ§Ã£o, AquisiÃ§Ã£o e ReorganizaÃ§Ã£o de Empresas e NegÃ³cios  
